module Rex
module Post
module Meterpreter
module Extensions
module Jailgun

TLV_TYPE_JAILGUN_THROWN = TLV_META_TYPE_BOOL | (TLV_EXTENSIONS + 1);
TLV_TYPE_JAILGUN_OBJREF = TLV_META_TYPE_UINT | (TLV_EXTENSIONS + 2);
TLV_TYPE_JAILGUN_CLASSNAME = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3);
TLV_TYPE_JAILGUN_METHODNAME = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 4);
TLV_TYPE_JAILGUN_PARAMETERTYPES = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 5);
TLV_TYPE_JAILGUN_ARGUMENTS = TLV_META_TYPE_RAW | (TLV_EXTENSIONS + 6);

end
end
end
end
end